In [1]:
# Đoạn code này tự động lấy Tên tài khoản và Tên máy tính
import getpass
import socket
user = getpass.getuser()
host = socket.gethostname()
def get_system_context():
    user = getpass.getuser()
    host = socket.gethostname()
    return f"[USER: {user}] [HOST: {host}]"

In [2]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

In [3]:
listings_df_raw = spark.read.format("csv") \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .option("quote", '"') \
    .option("escape", '"') \
    .option("multiLine", "true") \
    .load("../data/Listings.csv")
    # .load("hdfs://master-node:9000/AirbnbData/Listings.csv")  # dùng khi master-node bật
listings_df_raw.show(truncate=False)

+----------+---------------------------------------------------+--------+----------+----------------------------+------------------+------------------+--------------------+-----------------+-------------------------+--------------------+----------------------+-------------------+--------+-----+--------+---------+----------------+------------+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+--------------+--------------------+----------------------+-------------------------+---------------------+---------------------------+----------------------+-------------------+----------------+
|listing_id|name                                               |host_id |host_since|host_location               |host_response_time|host_response_rate|host_acceptance_rate|host_is_superhost|host_total_listings_count|host_has_profile_pic|host_identity_verified|neighbourhood      |district|city |latitude|longitude|property_type   |room_type   |accommodates|bedrooms|amenities                                                                                                                                                                                                                                                                                                                                                                                                         |price|minimum_nights|maximum_nights|review_scores_rating|review_scores_accuracy|review_scores_cleanliness|review_scores_checkin|review_scores_communication|review_scores_location|review_scores_value|instant_bookable|
+----------+---------------------------------------------------+--------+----------+----------------------------+------------------+------------------+--------------------+-----------------+-------------------------+--------------------+----------------------+-------------------+--------+-----+--------+---------+----------------+------------+------------+--------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+--------------+--------------+--------------------+----------------------+-------------------------+---------------------+---------------------------+----------------------+-------------------+----------------+
|281420    |Beautiful Flat in le Village Montmartre, Paris     |1466919 |2011-12-03|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |f                     |Buttes-Montmartre  |NULL    |Paris|48.88668|2.33343  |Entire apartment|Entire place|2           |1       |["Heating", "Kitchen", "Washer", "Wifi", "Long term stays allowed"]                                                                                                                                                                                                                                                                                                                                               |53   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|3705183   |39 mÂ² Paris (Sacre CÅ“ur)                         |10328771|2013-11-29|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Buttes-Montmartre  |NULL    |Paris|48.88617|2.34515  |Entire apartment|Entire place|2           |1       |["Shampoo", "Heating", "Kitchen", "Essentials", "Washer", "Dryer", "Wifi", "Long term stays allowed"]                                                                                                                                                                                                                                                                                                             |120  |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|4082273   |Lovely apartment with Terrace, 60m2                |19252768|2014-07-31|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |f                     |Elysee             |NULL    |Paris|48.88112|2.31712  |Entire apartment|Entire place|2           |1       |["Heating", "TV", "Kitchen", "Washer", "Wifi", "Long term stays allowed"]                                                                                                                                                                                                                                                                                                                                         |89   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|4797344   |Cosy studio (close to Eiffel tower)                |10668311|2013-12-17|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Vaugirard          |NULL    |Paris|48.84571|2.30584  |Entire apartment|Entire place|2           |1       |["Heating", "TV", "Kitchen", "Wifi", "Long term stays allowed"]                                                                                                                                                                                                                                                                                                                                                   |58   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|4823489   |Close to Eiffel Tower - Beautiful flat : 2 rooms   |24837558|2014-12-14|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |f                     |Passy              |NULL    |Paris|48.855  |2.26979  |Entire apartment|Entire place|2           |1       |["Heating", "TV", "Kitchen", "Essentials", "Hair dryer", "Washer", "Dryer", "Bathtub", "Wifi", "Elevator", "Long term stays allowed", "Cable TV"]                                                                                                                                                                                                                                                                 |60   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|4898654   |NEW - Charming apartment Le Marais                 |505535  |2011-04-13|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Temple             |NULL    |Paris|48.86428|2.3537   |Entire apartment|Entire place|2           |1       |["Heating", "TV", "Kitchen", "Essentials", "Washer", "Smoke alarm", "Wifi", "Long term stays allowed", "Cable TV"]                                                                                                                                                                                                                                                                                                |95   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|6021700   |2P - Entre Bastille et Republique                  |8053690 |2013-08-09|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Popincourt         |NULL    |Paris|48.86384|2.37101  |Entire apartment|Entire place|2           |1       |["Shampoo", "TV", "Kitchen", "Washer", "Smoke alarm", "Wifi", "Fire extinguisher", "Long term stays allowed"]                                                                                                                                                                                                                                                                                                     |80   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|6945740   |57sqm btw. Bastille & PÃ¨re Lachaise               |5924709 |2013-04-14|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Popincourt         |NULL    |Paris|48.86043|2.37842  |Entire apartment|Entire place|2           |1       |["Heating", "TV", "Kitchen", "Essentials", "Washer", "Dryer", "Smoke alarm", "Wifi", "Long term stays allowed"]                                                                                                                                                                                                                                                                                                   |59   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|7491966   |Charming appartment near the Parc Buttes Chaumont  |35812762|2015-06-14|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Buttes-Chaumont    |NULL    |Paris|48.87871|2.37489  |Entire apartment|Entire place|2           |1       |["Paid parking off premises", "Shampoo", "Heating", "TV", "Iron", "Kitchen", "Hair dryer", "Essentials", "Washer", "Hot water", "Hangers", "Smoke alarm", "Wifi", "Long term stays allowed", "Dedicated workspace", "Host greets you", "Cable TV"]                                                                                                                                                                |80   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|7849932   |Bel appartement plein de charme !                  |20833291|2014-09-02|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Opera              |NULL    |Paris|48.8779 |2.33122  |Entire apartment|Entire place|2           |1       |["Heating", "TV", "Iron", "Kitchen", "Essentials", "Hair dryer", "Washer", "Hangers", "Wifi", "Elevator", "Long term stays allowed", "Dedicated workspace", "Cable TV"]                                                                                                                                                                                                                                           |90   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|7995091   |Beau 2piÃ¨ces prÃ¨s Butte aux cailles              |35014275|2015-06-04|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Gobelins           |NULL    |Paris|48.82296|2.34667  |Entire apartment|Entire place|2           |1       |["Heating", "Kitchen", "Essentials", "Washer", "Carbon monoxide alarm", "Smoke alarm", "Wifi", "Long term stays allowed", "Cable TV"]                                                                                                                                                                                                                                                                             |60   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|9011901   |Cosy appartement in marais 40m2                    |19939276|2014-08-13|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Hotel-de-Ville     |NULL    |Paris|48.85681|2.35678  |Entire apartment|Entire place|2           |1       |["Shampoo", "Heating", "TV", "Kitchen", "Essentials", "Washer", "Dryer", "Smoke alarm", "Wifi", "Long term stays allowed", "Cable TV"]                                                                                                                                                                                                                                                                            |80   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|9880847   |Cosy Flat near Rue Mouffetard                      |18264466|2014-07-17|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |f                     |Pantheon           |NULL    |Paris|48.83855|2.35064  |Entire apartment|Entire place|2           |1       |["Heating", "Iron", "Kitchen", "Essentials", "Hair dryer", "Hangers", "Smoke alarm", "Wifi", "Long term stays allowed", "Dedicated workspace"]                                                                                                                                                                                                                                                                    |61   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|9898855   |Grand 2 piÃ¨ces de 60 m2 cosy au canal Saint Martin|10121410|2013-11-19|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Enclos-St-Laurent  |NULL    |Paris|48.87437|2.36208  |Entire apartment|Entire place|2           |1       |["Dishwasher", "Essentials", "Stove", "Hot water", "Hangers", "Smoke alarm", "Wifi", "Long term stays allowed", "Dedicated workspace", "TV", "Iron", "Dryer", "Refrigerator", "Oven", "Dishes and silverware", "Heating", "Kitchen", "Coffee maker", "Washer", "Cooking basics", "Paid parking off premises", "Garden or backyard", "Bed linens", "Carbon monoxide alarm", "Cleaning before checkout", "Elevator"]|145  |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|10266213  |Studio pour deux, place de clichy                  |52785202|2015-12-30|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Elysee             |NULL    |Paris|48.88074|2.32384  |Entire apartment|Entire place|2           |1       |["Heating", "TV", "Iron", "Kitchen", "Essentials", "Hair dryer", "Hangers", "Wifi", "Elevator", "Long term stays allowed"]                                                                                                                                                                                                                                                                                        |35   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|11643413  |Luminous & very cosy flat in Paris                 |34678556|2015-05-31|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |f                     |Popincourt         |NULL    |Paris|48.87064|2.37499  |Entire apartment|Entire place|2           |1       |["Heating", "TV", "Iron", "Kitchen", "Essentials", "Hair dryer", "Washer", "Hangers", "Smoke alarm", "Wifi", "Long term stays allowed", "Dedicated workspace"]                                                                                                                                                                                                                                                    |39   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |
|11764434  |2 piÃ¨ces baignees de soleil !                     |28504056|2015-02-28|Paris, Ile-de-France, France|NULL              |NULL              |NULL                |f                |1                        |t                   |t                     |Batignolles-Monceau|NULL    |Paris|48.88423|2.31339  |Entire apartment|Entire place|2           |1       |["Heating", "TV", "Kitchen", "Essentials", "Hair dryer", "Washer", "Smoke alarm", "Wifi", "Long term stays allowed"]                                                                                                                                                                                                                                                                                              |55   |2             |1125          |100                 |10                    |10                       |10                   |10                         |10                    |10                 |f               |

In [4]:
from pyspark.sql.functions import col, from_json
from pyspark.sql.types import ArrayType, StringType
listings_df = listings_df_raw.withColumn(
    "amenities",
    from_json(col("amenities"), ArrayType(StringType()))
)

In [5]:
from pyspark.sql.functions import when, col
# Quy đổi toàn bộ giá từ tiền tệ địa phương (Local Currency) sang USD
# Tỷ giá được cập nhật theo thời điểm hiện tại
listings_df_currency = listings_df.withColumn(
    "price_usd",
    when(col("city") == "New York", col("price") * 1.0)           # USD giữ nguyên
    .when(col("city") == "Paris", col("price") * 1.156)            # EUR -> USD
    .when(col("city") == "Rome", col("price") * 1.156)             # EUR -> USD
    .when(col("city") == "Sydney", col("price") * 0.7038)           # AUD -> USD
    .when(col("city") == "Hong Kong", col("price") * 0.1276)        # HKD -> USD
    .when(col("city") == "Bangkok", col("price") * 0.03048)         # THB -> USD
    .when(col("city") == "Mexico City", col("price") * 0.05795)     # MXN -> USD
    .when(col("city") == "Cape Town", col("price") * 0.06130)       # ZAR -> USD
    .when(col("city") == "Istanbul", col("price") *  0.02162)        # TRY -> USD
    .when(col("city") == "Rio de Janeiro", col("price") * 0.1961 )   # BRL -> USD
    .otherwise(col("price"))
)

In [6]:
listings_df_currency.show()

+----------+--------------------+--------+----------+--------------------+------------------+------------------+--------------------+-----------------+-------------------------+--------------------+----------------------+-------------------+--------+-----+--------+---------+----------------+------------+------------+--------+--------------------+-----+--------------+--------------+--------------------+----------------------+-------------------------+---------------------+---------------------------+----------------------+-------------------+----------------+------------------+
|listing_id|                name| host_id|host_since|       host_location|host_response_time|host_response_rate|host_acceptance_rate|host_is_superhost|host_total_listings_count|host_has_profile_pic|host_identity_verified|      neighbourhood|district| city|latitude|longitude|   property_type|   room_type|accommodates|bedrooms|           amenities|price|minimum_nights|maximum_nights|review_scores_rating|review_scores_accuracy|review_scores_cleanliness|review_scores_checkin|review_scores_communication|review_scores_location|review_scores_value|instant_bookable|         price_usd|
+----------+--------------------+--------+----------+--------------------+------------------+------------------+--------------------+-----------------+-------------------------+--------------------+----------------------+-------------------+--------+-----+--------+---------+----------------+------------+------------+--------+--------------------+-----+--------------+--------------+--------------------+----------------------+-------------------------+---------------------+---------------------------+----------------------+-------------------+----------------+------------------+
|    281420|Beautiful Flat in...| 1466919|2011-12-03|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     f|  Buttes-Montmartre|    NULL|Paris|48.88668|  2.33343|Entire apartment|Entire place|           2|       1|[Heating, Kitchen...|   53|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|61.267999999999994|
|   3705183|39 mÂ² Paris (Sac...|10328771|2013-11-29|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|  Buttes-Montmartre|    NULL|Paris|48.88617|  2.34515|Entire apartment|Entire place|           2|       1|[Shampoo, Heating...|  120|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|            138.72|
|   4082273|Lovely apartment ...|19252768|2014-07-31|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     f|             Elysee|    NULL|Paris|48.88112|  2.31712|Entire apartment|Entire place|           2|       1|[Heating, TV, Kit...|   89|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|102.88399999999999|
|   4797344|Cosy studio (clos...|10668311|2013-12-17|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|          Vaugirard|    NULL|Paris|48.84571|  2.30584|Entire apartment|Entire place|           2|       1|[Heating, TV, Kit...|   58|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|            67.048|
|   4823489|Close to Eiffel T...|24837558|2014-12-14|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     f|              Passy|    NULL|Paris|  48.855|  2.26979|Entire apartment|Entire place|           2|       1|[Heating, TV, Kit...|   60|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|             69.36|
|   4898654|NEW - Charming ap...|  505535|2011-04-13|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|             Temple|    NULL|Paris|48.86428|   2.3537|Entire apartment|Entire place|           2|       1|[Heating, TV, Kit...|   95|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|            109.82|
|   6021700|2P - Entre Bastil...| 8053690|2013-08-09|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|         Popincourt|    NULL|Paris|48.86384|  2.37101|Entire apartment|Entire place|           2|       1|[Shampoo, TV, Kit...|   80|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f| 92.47999999999999|
|   6945740|57sqm btw. Bastil...| 5924709|2013-04-14|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|         Popincourt|    NULL|Paris|48.86043|  2.37842|Entire apartment|Entire place|           2|       1|[Heating, TV, Kit...|   59|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|            68.204|
|   7491966|Charming appartme...|35812762|2015-06-14|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|    Buttes-Chaumont|    NULL|Paris|48.87871|  2.37489|Entire apartment|Entire place|           2|       1|[Paid parking off...|   80|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f| 92.47999999999999|
|   7849932|Bel appartement p...|20833291|2014-09-02|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|              Opera|    NULL|Paris| 48.8779|  2.33122|Entire apartment|Entire place|           2|       1|[Heating, TV, Iro...|   90|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|104.03999999999999|
|   7995091|Beau 2piÃ¨ces prÃ...|35014275|2015-06-04|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|           Gobelins|    NULL|Paris|48.82296|  2.34667|Entire apartment|Entire place|           2|       1|[Heating, Kitchen...|   60|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|             69.36|
|   9011901|Cosy appartement ...|19939276|2014-08-13|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|     Hotel-de-Ville|    NULL|Paris|48.85681|  2.35678|Entire apartment|Entire place|           2|       1|[Shampoo, Heating...|   80|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f| 92.47999999999999|
|   9880847|Cosy Flat near Ru...|18264466|2014-07-17|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     f|           Pantheon|    NULL|Paris|48.83855|  2.35064|Entire apartment|Entire place|           2|       1|[Heating, Iron, K...|   61|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f| 70.51599999999999|
|   9898855|Grand 2 piÃ¨ces d...|10121410|2013-11-19|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|  Enclos-St-Laurent|    NULL|Paris|48.87437|  2.36208|Entire apartment|Entire place|           2|       1|[Dishwasher, Esse...|  145|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|167.61999999999998|
|  10266213|Studio pour deux,...|52785202|2015-12-30|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|             Elysee|    NULL|Paris|48.88074|  2.32384|Entire apartment|Entire place|           2|       1|[Heating, TV, Iro...|   35|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|40.459999999999994|
|  11643413|Luminous & very c...|34678556|2015-05-31|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     f|         Popincourt|    NULL|Paris|48.87064|  2.37499|Entire apartment|Entire place|           2|       1|[Heating, TV, Iro...|   39|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|45.083999999999996|
|  11764434|2 piÃ¨ces baignee...|28504056|2015-02-28|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|Batignolles-Monceau|    NULL|Paris|48.88423|  2.31339|Entire apartment|Entire place|           2|       1|[Heating, TV, Kit...|   55|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|             63.58|
|  11963112|Appartement au co...|63894099|2016-03-21|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     f|         Popincourt|    NULL|Paris|48.85434|  2.37293|Entire apartment|Entire place|           2|       1|[Heating, TV, Iro...|   55|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|             63.58|
|  11985909|2 rooms Canal St ...| 6056099|2013-04-23|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|  Enclos-St-Laurent|    NULL|Paris| 48.8734|  2.36972|Entire apartment|Entire place|           2|       1|[Heating, Iron, K...|   57|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|            65.892|
|  12331902|      Calm 1 Bedroom|23193463|2014-10-31|Paris, Ile-de-Fra...|              NULL|              NULL|                NULL|                f|                        1|                   t|                     t|           Gobelins|    NULL|Paris|48.83767|  2.35554|Entire apartment|Entire place|           2|       1|[Heating, TV, Iro...|   55|             2|          1125|                 100|                    10|                       10|                   10|                         10|                    10|                 10|               f|             63.58|
+----------+--------------------+--------+----------+--------------------+------------------+------------------+--------------------+-----------------+-------------------------+--------------------+----------------------+-------------------+--------+-----+--------+---------+----------------+------------+------------+--------+--------------------+-----+--------------+--------------+--------------------+----------------------+-------------------------+---------------------+---------------------------+----------------------+-------------------+----------------+------------------+
only showing top 20 rows

In [7]:
listings_df_currency.printSchema()

root
 |-- listing_id: integer (nullable = true)
 |-- name: string (nullable = true)
 |-- host_id: integer (nullable = true)
 |-- host_since: date (nullable = true)
 |-- host_location: string (nullable = true)
 |-- host_response_time: string (nullable = true)
 |-- host_response_rate: double (nullable = true)
 |-- host_acceptance_rate: double (nullable = true)
 |-- host_is_superhost: string (nullable = true)
 |-- host_total_listings_count: integer (nullable = true)
 |-- host_has_profile_pic: string (nullable = true)
 |-- host_identity_verified: string (nullable = true)
 |-- neighbourhood: string (nullable = true)
 |-- district: string (nullable = true)
 |-- city: string (nullable = true)
 |-- latitude: double (nullable = true)
 |-- longitude: double (nullable = true)
 |-- property_type: string (nullable = true)
 |-- room_type: string (nullable = true)
 |-- accommodates: integer (nullable = true)
 |-- bedrooms: integer (nullable = true)
 |-- amenities: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- price: integer (nullable = true)
 |-- minimum_nights: integer (nullable = true)
 |-- maximum_nights: integer (nullable = true)
 |-- review_scores_rating: integer (nullable = true)
 |-- review_scores_accuracy: integer (nullable = true)
 |-- review_scores_cleanliness: integer (nullable = true)
 |-- review_scores_checkin: integer (nullable = true)
 |-- review_scores_communication: integer (nullable = true)
 |-- review_scores_location: integer (nullable = true)
 |-- review_scores_value: integer (nullable = true)
 |-- instant_bookable: string (nullable = true)
 |-- price_usd: double (nullable = true)

In [8]:
reviews_df=spark.read.csv("../data/Reviews.csv",header=True,inferSchema=True)
# reviews_df=spark.read.csv("hdfs://master-node:9000/AirbnbData/Reviews.csv",header=True,inferSchema=True)  # dùng khi master-node bật
reviews_df.show()

+----------+---------+----------+-----------+
|listing_id|review_id|      date|reviewer_id|
+----------+---------+----------+-----------+
|     11798|330265172|2018-09-30|   11863072|
|     15383|330103585|2018-09-30|   39147453|
|     16455|329985788|2018-09-30|    1125378|
|     17919|330016899|2018-09-30|  172717984|
|     26827|329995638|2018-09-30|   17542859|
|     74561|330089224|2018-09-30|  173044789|
|    140355|330194958|2018-09-30|  160093807|
|    162163|329980859|2018-09-30|   94026758|
|    167998|329950677|2018-09-30|   35388162|
|    178188|330213008|2018-09-30|    3652511|
|    232956|330140226|2018-09-30|   57664145|
|    266725|330038354|2018-09-30|   77387165|
|    314288|330299075|2018-09-30|  192717587|
|    325880|330081449|2018-09-30|  154527568|
|    335003|329968377|2018-09-30|    3461699|
|    348747|330131287|2018-09-30|    9554201|
|    352851|330201364|2018-09-30|  142182690|
|    378714|330246144|2018-09-30|   15772951|
|    406852|330283854|2018-09-30|   35469963|
|    406891|330095252|2018-09-30|  187332701|
+----------+---------+----------+-----------+
only showing top 20 rows

In [10]:
reviews_df.printSchema()

root
 |-- listing_id: integer (nullable = true)
 |-- review_id: integer (nullable = true)
 |-- date: date (nullable = true)
 |-- reviewer_id: integer (nullable = true)

In [9]:
listings_df_currency.createOrReplaceTempView("listings")
reviews_df.createOrReplaceTempView("reviews")
spark.catalog.listTables()

[Table(name='listings', catalog=None, namespace=[], description=None, tableType='TEMPORARY', isTemporary=True),
 Table(name='reviews', catalog=None, namespace=[], description=None, tableType='TEMPORARY', isTemporary=True)]

In [11]:
# Minh chứng số dòng > 100.000 dòng
spark.sql("SELECT COUNT(*) AS Total_rows FROM listings").show()

+----------+
|Total_rows|
+----------+
|    279712|
+----------+

In [12]:
# Minh chứng số cột >10
num_cols = len(listings_df.columns)
print(f"Tổng số cột: {num_cols}")

Tổng số cột: 33

In [13]:
# Câu truy vấn 2: Đánh giá hiệu quả của danh hiệu Superhost đối với việc thu hút khách hàng và chất lượng dịch vụ
print(f"{get_system_context()} [INFO]: Query execution started...")
spark.sql("""SELECT
   CASE L.host_is_superhost
       WHEN 't' THEN 'superhost'
       ELSE 'none'
   END AS host_is_superhost,
   COUNT(DISTINCT L.listing_id) AS total_listings,
   COUNT(R.review_id) AS reviews,
   ROUND(AVG(L.host_response_rate)*100, 2) AS avg_host_reponse,
   ROUND(AVG(L.host_acceptance_rate)*100, 2) AS avg_host_acceptance,
   ROUND(AVG(L.review_scores_rating), 2) AS avg_rating,
   ROUND(AVG(L.review_scores_cleanliness), 2) AS avg_cleanliness,
   ROUND(AVG(L.review_scores_communication), 2) AS avg_communication,
   ROUND(AVG(L.review_scores_value), 2) AS avg_value
FROM listings L
JOIN reviews R ON L.listing_id = R.listing_id
WHERE L.host_is_superhost IS NOT NULL
GROUP BY L.host_is_superhost
ORDER BY L.host_is_superhost ASC;""").toPandas()

[USER: Pham Hong Nhu] [HOST: LAPTOP-K48F5AJQ] [INFO]: Query execution started...

,host_is_superhost,total_listings,reviews,avg_host_reponse,avg_host_acceptance,avg_rating,avg_cleanliness,avg_communication,avg_value
0,none,147904,3009692,89.88,87.70,92.80,9.27,9.72,9.27
1,superhost,45540,2359512,97.24,93.37,96.85,9.79,9.97,9.73

In [14]:
# Câu truy vấn 3: Cơ cấu nguồn cung phòng và giá thuê theo quy mô sức chứa khách tại từng thành phố
print(f"{get_system_context()} [INFO]: Query execution started...")
spark.sql("""SELECT
   city,
   CASE
       WHEN accommodates <= 2 THEN '1-2 khách (Cá nhân/Cặp đôi)'
       WHEN accommodates BETWEEN 3 AND 5 THEN '3-5 khách (Gia đình/Nhóm nhỏ)'
       ELSE 'Trên 5 khách (Đoàn du lịch)'
   END AS room_capacity_segment,
   COUNT(listing_id) AS total_rooms_listed,
   ROUND(AVG(price_usd), 2) AS avg_nightly_price
FROM listings
WHERE accommodates IS NOT NULL
GROUP BY city,
   CASE
       WHEN accommodates <= 2 THEN '1-2 khách (Cá nhân/Cặp đôi)'
       WHEN accommodates BETWEEN 3 AND 5 THEN '3-5 khách (Gia đình/Nhóm nhỏ)'
       ELSE 'Trên 5 khách (Đoàn du lịch)'
   END
ORDER BY city,room_capacity_segment ASC;""").toPandas()

[USER: Pham Hong Nhu] [HOST: LAPTOP-K48F5AJQ] [INFO]: Query execution started...

,city,room_capacity_segment,total_rooms_listed,avg_nightly_price
0,Bangkok,1-2 khách (Cá nhân/Cặp đôi),10976,48.26
1,Bangkok,3-5 khách (Gia đình/Nhóm nhỏ),6288,64.54
2,Bangkok,Trên 5 khách (Đoàn du lịch),2097,138.71
3,Cape Town,1-2 khách (Cá nhân/Cặp đôi),8769,60.74
4,Cape Town,3-5 khách (Gia đình/Nhóm nhỏ),5814,97.71
5,Cape Town,Trên 5 khách (Đoàn du lịch),4503,380.47
6,Hong Kong,1-2 khách (Cá nhân/Cặp đôi),4912,69.18
7,Hong Kong,3-5 khách (Gia đình/Nhóm nhỏ),1486,132.99
8,Hong Kong,Trên 5 khách (Đoàn du lịch),689,199.31
9,Istanbul,1-2 khách (Cá nhân/Cặp đôi),12417,8.47
10,Istanbul,3-5 khách (Gia đình/Nhóm nhỏ),9302,11.20
11,Istanbul,Trên 5 khách (Đoàn du lịch),2800,26.05
12,Mexico City,1-2 khách (Cá nhân/Cặp đôi),11553,44.27
13,Mexico City,3-5 khách (Gia đình/Nhóm nhỏ),6395,81.85
14,Mexico City,Trên 5 khách (Đoàn du lịch),2117,142.35
15,New York,1-2 khách (Cá nhân/Cặp đôi),23074,103.01
16,New York,3-5 khách (Gia đình/Nhóm nhỏ),10914,175.47
17,New York,Trên 5 khách (Đoàn du lịch),3024,328.99
18,Paris,1-2 khách (Cá nhân/Cặp đôi),35019,94.98
19,Paris,3-5 khách (Gia đình/Nhóm nhỏ),24481,142.11
20,Paris,Trên 5 khách (Đoàn du lịch),5190,318.38
21,Rio de Janeiro,1-2 khách (Cá nhân/Cặp đôi),8257,77.25
22,Rio de Janeiro,3-5 khách (Gia đình/Nhóm nhỏ),11992,120.27
23,Rio de Janeiro,Trên 5 khách (Đoàn du lịch),6366,282.07
24,Rome,1-2 khách (Cá nhân/Cặp đôi),10463,92.89
25,Rome,3-5 khách (Gia đình/Nhóm nhỏ),12385,111.47
26,Rome,Trên 5 khách (Đoàn du lịch),4799,209.78
27,Sydney,1-2 khách (Cá nhân/Cặp đôi),18790,88.82
28,Sydney,3-5 khách (Gia đình/Nhóm nhỏ),9666,150.72
29,Sydney,Trên 5 khách (Đoàn du lịch),5174,411.49

In [9]:
#Câu truy vấn 4: Truy vấn phân chia phòng theo các phân khúc giá (Giá rẻ, Trung bình, Cao cấp) và tính điểm đánh giá trung bình (avg_rating) của từng phân khúc
print(f"{get_system_context()} [INFO]: Query execution started...")
spark.sql("""
SELECT
   CASE
       WHEN CAST(price AS DOUBLE) < 50 THEN '1. Gia re'
       WHEN CAST(price AS DOUBLE) BETWEEN 50 AND 150 THEN '2. Trung binh'
       ELSE '3. Cao cap'
   END AS price_tier,
   ROUND(AVG(CAST(review_scores_rating AS DOUBLE)), 2) AS avg_rating,
   COUNT(*) AS total_listings
FROM
   listings
WHERE
   price IS NOT NULL
   AND review_scores_rating IS NOT NULL
GROUP BY
   1
ORDER BY
   price_tier ASC;
""").toPandas()

[USER: DELL] [HOST: LE-VIET-BAO] [INFO]: Query execution started...

      price_tier  avg_rating  total_listings
0      1. Gia re       91.99           19577
1  2. Trung binh       93.31           83211
2     3. Cao cap       93.82           85519

In [10]:
#Câu truy vấn 5: Truy vấn thống kê top 20 tiện ích xuất hiện phổ biến nhất trên toàn bộ hệ thống
print(f"{get_system_context()} [INFO]: Query execution started...")
spark.sql("""
 SELECT
  exploded_amenity AS amenity_name,
  COUNT(*) AS tan_suat
 FROM listings
 LATERAL VIEW EXPLODE(amenities) AS exploded_amenity
 GROUP BY exploded_amenity
 ORDER BY tan_suat DESC LIMIT 20
""").toPandas()

[USER: DELL] [HOST: LE-VIET-BAO] [INFO]: Query execution started...

               amenity_name  tan_suat
0                      Wifi    260090
1                Essentials    253532
2   Long term stays allowed    241054
3                   Kitchen    240923
4                        TV    213037
5                   Hangers    211356
6                Hair dryer    188724
7                      Iron    187756
8                    Washer    185073
9                   Heating    184327
10      Dedicated workspace    179267
11                  Shampoo    174082
12                Hot water    165163
13              Smoke alarm    156467
14         Air conditioning    142693
15    Dishes and silverware    123394
16             Refrigerator    123259
17           Cooking basics    110255
18                 Elevator    101582
19               Bed linens    100486

In [11]:
#Câu truy vấn 6: Truy vấn tính toán tính ra tỷ trọng phần trăm của từng loại phòng trong mỗi khu vực
print(f"{get_system_context()} [INFO]: Query execution started...")
spark.sql ("""
SELECT
   neighbourhood,
   room_type,
   COUNT(*) AS total_listings,
   ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY neighbourhood), 2) AS pct_share_in_area
FROM listings
GROUP BY neighbourhood, room_type
ORDER BY neighbourhood, pct_share_in_area DESC;
""").toPandas()

[USER: DELL] [HOST: LE-VIET-BAO] [INFO]: Query execution started...

     neighbourhood     room_type  total_listings pct_share_in_area
0         Abolicao  Entire place               4             80.00
1         Abolicao   Shared room               1             20.00
2            Acari  Entire place               1            100.00
3           Adalar  Entire place             124             63.59
4           Adalar  Private room              60             30.77
...            ...           ...             ...               ...
1846   Zeytinburnu  Entire place              62             53.45
1847   Zeytinburnu  Private room              47             40.52
1848   Zeytinburnu   Shared room               6              5.17
1849   Zeytinburnu    Hotel room               1              0.86
1850         Zumbi  Entire place               1            100.00

[1851 rows x 4 columns]

In [15]:
# Câu truy vấn 7: Đánh giá các tiện ích cốt lõi thuộc phân khúc căn hộ Cao cấp
print(f"{get_system_context()} [INFO]: Query execution started...")
spark.sql("""SELECT
   exploded_amenity AS amenity_name,
   COUNT(*) AS total_occurrence
FROM listings
LATERAL VIEW EXPLODE(amenities) AS exploded_amenity
WHERE price_usd > (SELECT AVG(price_usd) FROM listings)
GROUP BY exploded_amenity
ORDER BY total_occurrence DESC
LIMIT 5;""").toPandas()

[USER: Pham Hong Nhu] [HOST: LAPTOP-K48F5AJQ] [INFO]: Query execution started...

              amenity_name  total_occurrence
0                     Wifi             66128
1               Essentials             62925
2                  Kitchen             62348
3  Long term stays allowed             60150
4                       TV             59949

In [12]:

#Câu truy vấn 8: Truy vấn khoanh vùng các khu vực kinh doanh trọng điểm trong mười hai tháng gần nhất  và trích xuất bộ chỉ số hiệu năng của ba căn hộ tối ưu nhất nội vùng làm đường cơ sở tiêu chuẩn.
print(f"{get_system_context()} [INFO]: Query execution started...")
spark.sql("""
WITH date_anchor AS (
   -- Bước 1: Tìm ngày đánh giá mới nhất thực tế có trong tập dữ liệu để làm mốc
   SELECT CAST(MAX(date) AS DATE) AS max_date FROM reviews
),
ltm_reviews_by_listing AS (
   -- Bước 2: Tính tổng số review LTM dựa trên ngày mốc vừa tìm được
   SELECT r.listing_id,
       COUNT(r.review_id) AS total_reviews_ltm
   FROM reviews r
   CROSS JOIN date_anchor a
   WHERE r.date >= CAST(DATE_SUB(a.max_date, 365) AS STRING)
   GROUP BY r.listing_id
   HAVING COUNT(r.review_id) > 0
),
ranked_listings AS (
   -- Bước 3: JOIN với bảng listings theo đúng trường 'listing_id'
   SELECT l.neighbourhood,l.listing_id,l.name,l.price,r.total_reviews_ltm,
       l.review_scores_cleanliness,l.review_scores_communication,
       ROW_NUMBER() OVER (PARTITION BY l.neighbourhood ORDER BY r.total_reviews_ltm DESC) AS hang_trong_vung
   FROM ltm_reviews_by_listing r
   JOIN listings l ON r.listing_id = l.listing_id ),
top_neighbourhoods AS (
   -- Bước 4: Lấy ra top các khu vực có tổng review LTM cao nhất
   SELECT neighbourhood,
       SUM(total_reviews_ltm) AS tong_reviews_khu_vuc
   FROM ranked_listings
   GROUP BY neighbourhood
   ORDER BY tong_reviews_khu_vuc DESC
   LIMIT 10
)
-- Bước 5: Xuất kết quả chi tiết
SELECT l.neighbourhood,l.listing_id,l.name,l.price,l.total_reviews_ltm,
   l.review_scores_cleanliness,l.review_scores_communication
FROM ranked_listings l
JOIN top_neighbourhoods n ON l.neighbourhood = n.neighbourhood
WHERE l.hang_trong_vung <= 3
ORDER BY n.tong_reviews_khu_vuc DESC,l.total_reviews_ltm DESC;
""").toPandas()

[USER: DELL] [HOST: LE-VIET-BAO] [INFO]: Query execution started...

,neighbourhood,listing_id,name,price,total_reviews_ltm,review_scores_cleanliness,review_scores_communication
0,Cuauhtemoc,43246311,Habitacion para estancias largas,518,194,10.0,10.0
1,Cuauhtemoc,45175157,Habitacion Privada en el Corazon de la Roma,642,158,9.0,10.0
2,Cuauhtemoc,46547879,Habitacion privada en el Zocalo de la Ciudad,651,131,10.0,10.0
3,I Centro Storico,32185249,Romantic suite in Campo de Fiori,91,110,10.0,10.0
4,I Centro Storico,23880958,REAL BEST VIEW COLISEUM LUXURY LOFT HISTORY CE...,68,75,10.0,10.0
5,I Centro Storico,17680772,Valentine's Day Special Offer,30,73,10.0,10.0
6,Beyoglu,21811046,Well Designed Studio Apartment in BEYOGLU,252,181,9.0,10.0
7,Beyoglu,32186550,@KarakÃ¶y Nice Big Studio Apartment,171,141,10.0,10.0
8,Beyoglu,34331518,Zen Apartments 4,144,84,9.0,10.0
9,Copacabana,35386228,COPACABANA LUXO & DESIGN SELF CHECK IN 24 HORAS,260,114,10.0,10.0
10,Copacabana,28737202,COPACABANA DESIGN & STYLE PLUS SELF CHECK IN,274,83,10.0,10.0
11,Copacabana,17865987,"Copacabana beach airbnb plus, Vibrant Apartment",254,78,10.0,10.0
12,Sydney,43024746,The perfect place to getaway.,133,429,9.0,10.0
13,Sydney,42693214,Long Stay Special- Studio Apartment,91,291,10.0,10.0
14,Sydney,43240235,Metro Aspire Hotel Sydney - Premium Room,123,226,10.0,9.0
15,Miguel Hidalgo,42224748,"New & Clean Apt in Polanco, w/ rooftop, gym & ...",1536,142,9.0,10.0
16,Miguel Hidalgo,42272228,"""Clean & New Apt"" Polanco balcony, pool, roof,...",1263,118,9.0,10.0
17,Miguel Hidalgo,19160175,Comodo y seguro Loft cerca de Polanco,633,109,9.0,10.0
18,Ward 115,43084815,WINK at Foreshore - Studio Apartments,1078,75,9.0,10.0
19,Ward 115,32716717,508 - Great Value in Central Cape Town,975,69,10.0,10.0
20,Ward 115,4646142,"Unwind in a Bright, Airy Space with Rustic Acc...",529,68,NaN,NaN
21,Benito Juarez,40232453,Bonito centrico LOFT C/Jacuzzi en terraza privada,809,138,10.0,10.0
22,Benito Juarez,38828041,"âš¡ AMAZING apartment, great location âš¡ 331",684,124,10.0,10.0
23,Benito Juarez,30355386,"âš¡ AMAZING apartment, great location âš¡ 221",673,114,10.0,10.0
24,Popincourt,41020735,Lit dans Dortoir Mixte de 8 Lits â€œThe Big On...,25,112,10.0,10.0
25,Popincourt,24073460,Paris Little Voltaire,66,98,10.0,10.0
26,Popincourt,11663484,Nice studio in the heart of Oberkampf,41,79,9.0,10.0
27,Bedford-Stuyvesant,36900144,2 bedroom suite all to yourself. Manhattan 20 ...,157,92,10.0,10.0
28,Bedford-Stuyvesant,18890521,Private 3 bedroom Apartment 3 blocks from subway,385,86,10.0,10.0
29,Bedford-Stuyvesant,18565752,"""WELCOME TO BROOKLYN"" PARK SIDE VIEW STUDIO APT",85,84,10.0,10.0

In [10]:

# QUERY 1 – Diem hanh vi tot & ty le Superhost
print(f"{get_system_context()} [INFO]: Query execution started...")
spark.sql("""
  SELECT diem_hanh_vi_tot,
         COUNT(*)                       AS so_listing,
         ROUND(100.0*AVG(la_super), 2)  AS ty_le_superhost
  FROM (
      SELECT CASE WHEN host_is_superhost = 't' THEN 1 ELSE 0 END AS la_super,
             ( CASE WHEN host_response_time   = 'within an hour' THEN 1 ELSE 0 END
             + CASE WHEN host_identity_verified = 't'            THEN 1 ELSE 0 END
             + CASE WHEN instant_bookable       = 't'            THEN 1 ELSE 0 END ) AS diem_hanh_vi_tot
      FROM listings
  )
  GROUP BY diem_hanh_vi_tot
  ORDER BY diem_hanh_vi_tot
""").toPandas()

[USER: Quynh Nga] [HOST: DESKTOP-TC9PES0] [INFO]: Query execution started...

   diem_hanh_vi_tot  so_listing  ty_le_superhost
0                 0       40076             5.97
1                 1      118466            12.59
2                 2       81714            23.74
3                 3       39456            34.33

In [11]:
# Câu truy vấn số 9 Làm thế nào để nhận diện sớm các Superhost đang có nguy cơ tụt hạng trước kỳ đánh giá tiếp theo của Airbnb?
print(f"{get_system_context()} [INFO]: Query execution started...")
spark.sql("""
WITH host_agg AS (
 SELECT host_id, FIRST(city) AS city, COUNT(*) AS n_listing,
        ROUND(AVG(review_scores_rating),2)  AS rating_tb,
        MAX(host_is_superhost) AS is_super
 FROM listings
 WHERE review_scores_rating IS NOT NULL
 GROUP BY host_id
 HAVING MAX(host_is_superhost) = 't'
),
city_bench AS (
 SELECT city, AVG(rating_tb) AS rating_city FROM host_agg GROUP BY city
),
RankedAnalysis AS (
 SELECT h.host_id, h.city, h.n_listing, h.rating_tb,
        ROUND(h.rating_tb - c.rating_city, 2) AS lech_vs_city,
        NTILE(4) OVER (ORDER BY h.rating_tb) AS nhom_rui_ro,
        CASE WHEN h.rating_tb < c.rating_city THEN 'SUPERHOST RUI RO'
             ELSE 'OK' END AS canh_bao
 FROM host_agg h JOIN city_bench c ON h.city = c.city
 WHERE h.n_listing >= 2
)
SELECT host_id, city, n_listing, rating_tb, lech_vs_city, nhom_rui_ro, canh_bao
FROM (
 SELECT *,
        ROW_NUMBER() OVER (PARTITION BY nhom_rui_ro ORDER BY lech_vs_city ASC) AS thut_tu_trong_nhom
 FROM RankedAnalysis
)
WHERE thut_tu_trong_nhom <= 5
ORDER BY nhom_rui_ro ASC, lech_vs_city ASC
""").toPandas()

[USER: Quynh Nga] [HOST: DESKTOP-TC9PES0] [INFO]: Query execution started...

,host_id,city,n_listing,rating_tb,lech_vs_city,nhom_rui_ro,canh_bao
0,309651408,Cape Town,2,50.00,-47.68,1,SUPERHOST RUI RO
1,125422956,Sydney,2,58.50,-39.16,1,SUPERHOST RUI RO
2,31168193,Cape Town,2,70.00,-27.68,1,SUPERHOST RUI RO
3,152690866,Istanbul,5,71.00,-26.28,1,SUPERHOST RUI RO
4,274418925,Bangkok,3,71.67,-25.40,1,SUPERHOST RUI RO
5,278252599,Mexico City,2,96.00,-1.68,2,SUPERHOST RUI RO
6,271659755,Mexico City,2,96.00,-1.68,2,SUPERHOST RUI RO
7,239389564,Mexico City,3,96.00,-1.68,2,SUPERHOST RUI RO
8,211773688,Mexico City,3,96.00,-1.68,2,SUPERHOST RUI RO
9,196839762,Mexico City,2,96.00,-1.68,2,SUPERHOST RUI RO
10,309591724,Rio de Janeiro,4,97.50,-0.17,3,SUPERHOST RUI RO
11,303098280,Rio de Janeiro,2,97.50,-0.17,3,SUPERHOST RUI RO
12,228016212,Rio de Janeiro,2,97.50,-0.17,3,SUPERHOST RUI RO
13,218304025,Rio de Janeiro,2,97.50,-0.17,3,SUPERHOST RUI RO
14,175089125,Rio de Janeiro,2,97.50,-0.17,3,SUPERHOST RUI RO
15,374613808,Mexico City,3,99.00,1.32,4,OK
16,343758906,Mexico City,2,99.00,1.32,4,OK
17,329501693,Mexico City,3,99.00,1.32,4,OK
18,251605680,Mexico City,3,99.00,1.32,4,OK
19,251150365,Mexico City,3,99.00,1.32,4,OK

In [12]:
# Câu truy vấn số 10 Tỷ lệ Superhost phân bố như thế nào giữa các loại hình phòng tại từng thành phố?
print(f"{get_system_context()} [INFO]: Query execution started...")
spark.sql("""
SELECT * FROM (
SELECT city, room_type,
       CASE WHEN host_is_superhost='t' THEN 1.0 ELSE 0.0 END AS is_super
FROM listings
) PIVOT (
ROUND(AVG(is_super)*100, 1)
FOR room_type IN ('Entire place' AS entire, 'Private room' AS private,
                  'Hotel room' AS hotel, 'Shared room' AS shared)
)
""").toPandas()

[USER: Quynh Nga] [HOST: DESKTOP-TC9PES0] [INFO]: Query execution started...

             city entire private hotel shared
0          Sydney   13.8     9.7  22.7    2.5
1     Mexico City   39.8    23.1  25.2   18.9
2       Cape Town   27.6    14.5  11.4    7.1
3           Paris   12.0    15.7  20.3    8.5
4        Istanbul   18.0     7.8  14.8    6.0
5       Hong Kong   14.6    21.7   3.9   13.7
6            Rome   30.4    18.4  18.4   10.0
7  Rio de Janeiro   18.7    13.1  26.3    8.7
8         Bangkok   25.7    12.6  16.1   15.0
9        New York   20.0    17.6  14.4   15.7

In [ ]:
u27t8a58